baseURL = "https://shizuku.icu/"
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
disablePathToLower = false
enableEmoji = false
enableGitInfo = false
enableRobotsTXT = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
languageCode = "zh-CN"
newContentEditor = ""
paginate = 5
pluralizeListTitles = false
relativeURLs = false
summaryLength = 42
theme = "meme"
title = "雫 / Shizuku"
uglyURLs = false
[author]
avatar = "https://natsuka-cos-1302639736.file.myqcloud.com/saki/android-chrome-512x512.png"
email = "saki@hikarimind.xyz"
motto = "Rainy Umbrella"
name = "Kawasaki Shizuku"
twitter = "kawasakishizuku"
website = "https://saki-memo.xyz/"
[frontmatter]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = false
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false
[markup.highlight]
codeFences = true
guessSyntax = false
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 6
ordered = true
startLevel = 2
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]
[[menu.main]]
name = "文章"
pre = "internal"
url = "/posts/"
weight = 2
[[menu.main]]
name = "几句"
pre = "internal"
url = "/something/"
weight = 3
[[menu.main]]
name = "标签"
pre = "internal"
url = "/tags/"
weight = 4
[[menu.main]]
name = "关于"
pre = "internal"
url = "/about/"
weight = 5
[[menu.main]]
identifier = "theme-switcher"
weight = 6
[[menu.main]]
identifier = "lang-switcher"
weight = 7
[outputFormats.SectionsAtom]
baseName = "atom"
mediaType = "application/atom+xml"
[outputFormats.SectionsRSS]
baseName = "rss"
mediaType = "application/rss+xml"
[outputs]
home = ["HTML", "SectionsAtom", "SectionsRSS"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
[params]
activeInSection = false
anchorIcon = "link"
anchorSymbol = "#"
autoDetectImages = true
autoHideLangToggle = true
autoLoadComments = false
backToTopIcon = "arrow-up"
badgeTitlePrefix = "Updated @ "
busuanziPagePVIcon = "eye"
busuanziSitePVIcon = "eye"
busuanziSitePVText = "本站访问量"
busuanziSiteUVIcon = "user"
busuanziSiteUVText = "本站访客数"
captionPrefix = "◎ "
categoryBy = "sections"
categoryDelimiter = "/"
categoryIcon = "folder"
chineseZodiac = true
customFooter = ""
defaultTheme = "light"
deleteHrBeforeDropCap = false
disableMathJaxMenu = false
displayBackToTopInHome = true
displayBackToTopOnMobile = false
displayBusuanziPagePV = false
displayBusuanziSiteUVAndPV = false
displayCategory = true
displayCommitHash = true
displayCommitMessage = true
displayCopyrightSymbol = true
displayEditLink = true
displayExpiredDate = true
displayFeedback = true
displayFooter = false
displayFooterInHome = true
displayHeaderInHome = true
displayListTitle = true
displayMenuInHome = true
displayModifiedDate = true
displayPostCopyright = true
displayPostDescription = true
displayPostGitInfo = false
displayPostShare = true
displayPosts = true
displayPostsCount = true
displayPoweredBy = false
displayPublishedDate = true
displayReadingTime = true
displayRelatedPosts = true
displayShareOnText = false
displaySiteCopyright = false
displaySiteCreatedYear = true
displayTOCNum = true
displayTOCTitle = true
displayTaxonomyTermCount = true
displayUpdatedBadge = true
displayWordCount = true
disqusShortname = ""
duration = 0.5
editIcon = "edit"
editText = "Edit Me?"
enableAboutPageMinimalFooter = false
enableAnchorAutoHide = true
enableAnchorLink = true
enableBackToTop = true
enableBackToTopAutoHide = true
enableBadgeTitle = true
enableCaption = true
enableChinesePunctuationGlyphCorrection = true
enableComments = false
enableCopy = true
enableCopyAutoHide = true
enableDarkMode = true
enableDisqus = false
enableDropCap = false
enableDropCapAfterHr = false
enableEmphasisPoint = true
enableFingerprint = true
enableFooter = true
enableForceHTTPS = false
enableGitalk = false
enableGoogleAdUnits = false
enableGoogleAnalytics = false
enableGoogleAutoAds = false
enableHeader = true
enableHeaderAutoHide = true
enableHeadingsAnchor = true
enableHighlight = true
enableImageHost = false
enableInstantPage = true
enableJustify = true
enableKaTeX = false
enableLangToggle = false
enableLunrSearch = false
enableMathJax = false
enableMediumZoom = true
enableMenu = true
enableMermaid = false
enableMinimalFooter = true
enableNavToggle = true
enableOverflowY = true
enableParagraphIndent = true
enablePostCopyright = true
enablePostGitInfo = false
enablePostMeta = true
enablePostMetaInHome = true
enablePostNav = true
enablePostShare = true
enablePostTags = true
enablePostUpdatedBadge = true
enableRelatedPosts = true
enableSRI = false
enableServiceWorker = true
enableSmallCaps = false
enableSmoothScroll = true
enableSocials = false
enableTOC = false
enableTagCloud = true
enableTree = true
enableUtterances = false
enableValine = false
enableVerticalBarStructure = true
enableVideoHost = false
expiredDateIcon = "calendar-times"
feedbackIcon = "question"
feedbackText = "Feedback"
fofPoster = ""
fofVideoMp4 = ""
fofVideoWebm = ""
fontFamilyBody = "'EB Garamond', 'Noto Serif SC', serif"
fontFamilyCaption = ""
fontFamilyCode = "'Source Code Pro', 'Noto Serif SC', monospace"
fontFamilyFooter = ""
fontFamilyHeadings = "'Noto Serif SC', 'EB Garamond', serif"
fontFamilyMenu = ""
fontFamilyQuote = ""
fontFamilySiteBrand = ""
fontFamilyTOC = ""
fontFamilyTitle = "'Noto Serif SC', 'EB Garamond', serif"
fontSize = 16
fontUnit = "em"
fontsLink = "https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,700;1,400;1,700&family=Noto+Serif+SC:wght@400;500;700&family=Source+Code+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap"
footnoteReturnLinkIcon = "angle-up"
gitIcon = "code-branch"
gitalkAdmin = ["your_gitalk_admin"]
gitalkClientID = "your_client_id"
gitalkClientSecret = "your_client_secret"
gitalkCreateIssueManually = false
gitalkDistractionFreeMode = false
gitalkEnableHotKey = true
gitalkLable = ["Gitalk"]
gitalkLanguage = "en"
gitalkOwner = "your_gitalk_owner"
gitalkPagerDirection = "last"
gitalkPerPage = 10
gitalkProxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"
gitalkRepo = "your_repository"
googleAdClient = ""
googleAdSlot = ""
googleSiteVerification = ""
groupByMonth = true
headAlso = false
headerBackground = "linear-gradient(90deg, #f795331a 0, #f370551a 15%, #ef4e7b1a 30%, #a166ab1a 44%, #5073b81a 58%, #1098ad1a 72%, #07b39b1a 86%, #6dba821a 100%)"
headerLayout = "flex"
headingsOpt = "1-6"
hideLangToggleInHome = false
hideThemeToggle = false
hideThemeToggleInHome = false
homeDescription = ""
homeKeywords = ""
homeLayout = "poetry"
homeLinksDelimiter = ""
homeLinksPadding = 1
homeLogo = ""
homeLogoLink = ""
homeMotto = ""
homePoetry = ["走到途中才忽然发现 <br /><br /> 我只剩下一副模糊的面目 <br /><br /> 和一条不能回头的路"]
homePoster = ""
homeTitle = ""
homeVideoMp4 = ""
homeVideoWebm = ""
hrefTargetBlank = true
i18nMonth = true
i18nYear = true
iconAnimation = true
iconBetweenYearAndAuthor = ""
iconColor = "#f06292"
imageHostURL = "https://example.com/"
includeContent = true
indentFirstParagraph = false
insertHrBySelf = true
jsonLD = true
largestFontSize = 2.5
limitEntriesLimit = -1
limitPostsLimit = -1
lineHeight = 2
linkHeadingsToTOC = true
listDateFormat = "1 月 2 日"
listDatePosition = "right"
listWidth = 36
mainSections = ["posts", "something"]
maxHeight = 20
mermaidTheme = "default"
mermaidThemeDark = "dark"
modifiedDateIcon = "calendar-check"
msApplicationTileColor = "#fff"
msgIcon = "info"
navHeight = "6em"
openGraph = true
original = true
overrideSystemPreferences = false
paragraphStyle = "margin"
postMetaDateFormat = "2006.1.2"
postNavInSection = true
postTagsIcon = "tag"
postWidth = 36
primaryColorDark = "201, 65%, 62%"
primaryColorLight = "220, 90%, 56%"
publishedDateIcon = "calendar-alt"
readingTimeIcon = "clock"
relatedPostsIcon = "plus-circle"
relatedPostsNumber = 5
repoEditURL = ""
repoURL = ""
safariMaskColor = "#2a6df4"
shareOnDouban = false
shareOnFacebook = true
shareOnLinkedIn = false
shareOnQQ = true
shareOnQzone = true
shareOnTelegram = true
shareOnTwitter = true
shareOnWeibo = true
shareViaQRCode = true
siteBrandFontColor = "var(--color-contrast-high)"
siteBrandFontSize = 1
siteBrandSVG = false
siteBrandSVGFill = "#fff"
siteBrandSVGHeight = 100
siteBrandSVGWidth = 250
siteCreatedTime = "2021-05-09T17:29:43+08:00"
siteDescription = "你好，欢迎来到我的站点。来自冷与的个人文字站点Shizuku，欢迎订阅 "
siteLogo = "https://natsuka-cos-1302639736.file.myqcloud.com/saki/android-chrome-512x512.webp"
siteTwitter = "kawasakishizuku"
smallestFontSize = 1
squareBrackets = true
tabSize = 4
themeColor = "#fff"
themeColorDark = "#16171d"
trackingCodeType = "gtag"
trackingID = ""
twitterCards = true
utterancesIssueTerm = "pathname"
utterancesLabel = ""
utterancesRepo = ""
utterancesTheme = "github-light"
utterancesThemeDark = "photon-dark"
valineAppId = ""
valineAppKey = ""
valineAvatar = "mm"
valineAvatarForce = false
valineEmojiCDN = ""
valineEnableQQ = false
valineHighlight = true
valineLang = "zh-cn"
valineMeta = ["nick", "mail", "link"]
valinePageSize = 10
valinePath = ""
valinePlaceholder = "Just go go"
valineRecordIP = false
valineRequiredFields = []
valineServerURLs = ""
valineVisitor = false
videoHostURL = "https://example.com/"
wordCountIcon = "pencil-alt"
yandexMetrikaId = ""
[params.valineEmojiMaps]
[permalinks]
categories = "/categories/:slug/"
tags = "/tags/:slug/"
[related]
includeNewer = true
threshold = 80
toLower = true
[[related.indices]]
name = "categories"
weight = 100
[[related.indices]]
name = "tags"
weight = 95
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[services.rss]
limit = -1
[taxonomies]
tag = "tags"
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
